version: '3.8'
services:
    consolidacao-app:
        container_name: consolidacao-app
        build:
            context: ../../
            dockerfile: ./images/php/Dockerfile
        depends_on:
            - consolidacao-mysql
        links:
            - consolidacao-mysql
        ports:
            - "8080:80"
        networks:
            - consolidacao-app-network
        volumes:
            - type: bind
              source: ./public
              target: /var/www/html
            #- ./config/apache/default.conf:/etc/apache2/sites-enabled/default.conf
    consolidacao-mysql:
        platform: linux/x86_64
        container_name: consolidacao-mysql
        image: mysql
        restart: always
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        ports:
            - "3306:3306"
        networks:
            - consolidacao-app-network
            - consolidacao-database-network
        volumes:
            - ./storage/mysql:/var/lib/mysql
    consolidacao-phpmyadmin:
        container_name: consolidacao-phpmyadmin
        image: phpmyadmin
        ports:
            - "3305:80"
        restart: always
        environment:
            PMA_HOST: consolidacao-mysql
            PMA_PASSWORD: ""
        depends_on:
            - consolidacao-mysql
        networks:
            - consolidacao-database-network
volumes:
    source:
networks:
  consolidacao-app-network:
  consolidacao-database-network:
